SELECT o.orderID,
       c.city
FROM orders AS o
INNER JOIN customers AS c
USING(customerID);

-- # List each order with its order date, product name, and quantity sold.
SELECT o.OrderID,
       o.OrderDate,
       p.ProductNAME,
       od.Quantity
FROM orders AS o
INNER JOIN order_details AS od
USING (OrderID)
INNER JOIN products AS p
USING (ProductID);

-- # Identify the top three cities that generated the highest total revenue.
SELECT c.City,
       SUM(od.UnitPrice * Quantity) AS total_revenue
FROM customers AS c
INNER JOIN orders AS o
USING(CustomerID)
INNER JOIN order_details AS od
USING(OrderID)
GROUP BY c.City
ORDER BY total_revenue DESC
LIMIT 3;

-- # Calculate the average order revenue for each city and rank cities from highest to lowest average order revenue.
SELECT
    sub.City,
    AVG(sub.revenue) AS avg_order_revenue
FROM (
    SELECT
        c.City,
        o.OrderID,
        SUM(od.UnitPrice * od.Quantity) AS revenue
    FROM customers AS c
    INNER JOIN orders AS o
        USING (CustomerID)
    INNER JOIN order_details AS od
        USING (OrderID)
    GROUP BY c.City, o.OrderID
) AS sub
GROUP BY sub.City
ORDER BY avg_order_revenue DESC;

-- # Identify the city that generated the highest total profit.
SELECT c.City,
      SUM((od.UnitPrice - od.UnitCost)*od.Quantity) AS profit
FROM customers AS c
INNER JOIN orders As o
USING(CustomerID)
INNER JOIN order_details AS od
USING(OrderID)
GROUP BY c.City 
ORDER BY profit  DESC
LIMIT 1;


-- # Compare the total number of orders between May and June 2026.
SELECT 
  CASE
        WHEN OrderDate >= '2026-05-01'
             AND OrderDate < '2026-06-01'
            THEN 'MAY 2026'
        WHEN OrderDate >= '2026-06-01'
             AND OrderDate < '2026-07-01'
            THEN 'JUNE 2026'
    END AS month,
    COUNT(OrderID) AS total_orders
    FROM orders 
    WHERE OrderDate >= '2026-05-01'
  AND OrderDate < '2026-07-01'
GROUP BY month
ORDER BY month;


-- # Compare the average order revenue between May and June 2026.
SELECT
    CASE
        WHEN OrderDate >= '2026-05-01'
             AND OrderDate < '2026-06-01'
            THEN 'MAY 2026'
        WHEN OrderDate >= '2026-06-01'
             AND OrderDate < '2026-07-01'
            THEN 'JUNE 2026'
    END AS month,
    AVG(sub.revenue) AS avg_revenue
FROM (
    SELECT OrderID,
           SUM(UnitPrice * Quantity) AS revenue
    FROM order_details
    GROUP BY OrderID
) AS sub
INNER JOIN orders
USING (OrderID)
WHERE OrderDate >= '2026-05-01'
  AND OrderDate < '2026-07-01'
GROUP BY month
ORDER BY month;

-- # Compare the total quantity of products sold between May and June 2026.
SELECT
    CASE
        WHEN o.OrderDate >= '2026-05-01'
             AND o.OrderDate < '2026-06-01'
            THEN 'MAY 2026'
        WHEN o.OrderDate >= '2026-06-01'
             AND o.OrderDate < '2026-07-01'
            THEN 'JUNE 2026'
    END AS month,
    SUM(od.Quantity) AS total_quantity
FROM orders AS o
INNER JOIN order_details AS od
    USING (OrderID)
WHERE o.OrderDate >= '2026-05-01'
  AND o.OrderDate < '2026-07-01'
GROUP BY month
ORDER BY month;

-- # Compare the average unit price of products sold between May and June 2026.
SELECT
    CASE
        WHEN o.OrderDate >= '2026-05-01'
         AND o.OrderDate < '2026-06-01'
        THEN 'MAY 2026'
 WHEN o.OrderDate >= '2026-06-01'
         AND o.OrderDate < '2026-07-01'
        THEN 'JUNE 2026'
    END AS month,
AVG(od.UnitPrice) AS avg_unit_price
FROM orders AS o
INNER JOIN order_details AS od
USING (OrderID)
WHERE o.OrderDate >= '2026-05-01'
  AND o.OrderDate < '2026-07-01'
GROUP BY month
ORDER BY month;

-- # Compare the average discount rate applied to sales between May and June 2026.
SELECT
    CASE
        WHEN o.OrderDate >= '2026-05-01'
         AND o.OrderDate < '2026-06-01'
        THEN 'MAY 2026'
 WHEN o.OrderDate >= '2026-06-01'
         AND o.OrderDate < '2026-07-01'
        THEN 'JUNE 2026'
    END AS month,
AVG(od.DiscountRate) AS avg_discount
FROM orders AS o
INNER JOIN order_details AS od
USING (OrderID)
WHERE o.OrderDate >= '2026-05-01'
  AND o.OrderDate < '2026-07-01'
GROUP BY month
ORDER BY month;


-- # Compare the revenue generated by each city between May and June 2026.
SELECT
    CASE
        WHEN o.OrderDate >= '2026-05-01'
             AND o.OrderDate < '2026-06-01'
            THEN 'MAY 2026'
        WHEN o.OrderDate >= '2026-06-01'
             AND o.OrderDate < '2026-07-01'
            THEN 'JUNE 2026'
    END AS month,
    c.City,
    SUM(od.UnitPrice * od.Quantity) AS revenue
FROM customers AS c
INNER JOIN orders AS o
    USING (CustomerID)
INNER JOIN order_details AS od
    USING (OrderID)
WHERE o.OrderDate >= '2026-05-01'
  AND o.OrderDate < '2026-07-01'
GROUP BY month,
         c.City
ORDER BY month,
         revenue DESC;


-- # Identify cities where revenue declined by more than 20% from May to June 2026.
WITH city_may_revenue AS (
    SELECT
        c.City,
        SUM(od.UnitPrice * od.Quantity) AS may_revenue
    FROM customers AS c
    INNER JOIN orders AS o
        USING (CustomerID)
    INNER JOIN order_details AS od
        USING (OrderID)
    WHERE o.OrderDate >= '2026-05-01'
      AND o.OrderDate < '2026-06-01'
    GROUP BY c.City
),
city_june_revenue AS (
    SELECT
        c.City,
        SUM(od.UnitPrice * od.Quantity) AS june_revenue
    FROM customers AS c
    INNER JOIN orders AS o
        USING (CustomerID)
    INNER JOIN order_details AS od
        USING (OrderID)
    WHERE o.OrderDate >= '2026-06-01'
      AND o.OrderDate < '2026-07-01'
    GROUP BY c.City
),
city_comparison AS (
    SELECT
        m.City,
        m.may_revenue,
        COALESCE(j.june_revenue, 0) AS june_revenue,

        COALESCE(j.june_revenue, 0) - m.may_revenue
            AS revenue_change,

        CASE
            WHEN COALESCE(j.june_revenue, 0) > m.may_revenue
                THEN 'City improved'
            WHEN COALESCE(j.june_revenue, 0) < m.may_revenue
                THEN 'City declined'
            ELSE 'No change'
        END AS performance,

        (
            COALESCE(j.june_revenue, 0) - m.may_revenue
        ) * 100.0 / m.may_revenue
            AS percentage_change
    FROM city_may_revenue AS m
    LEFT JOIN city_june_revenue AS j
        USING (City)
)
SELECT
    City,
    may_revenue,
    june_revenue,
    revenue_change,
    percentage_change
FROM city_comparison
WHERE percentage_change < -20
ORDER BY percentage_change ASC;
 