SELECT p.productNAME,
       c.categoryNAME
FROM products AS p
LEFT JOIN categories AS c
USING(categoryID);

-- # List all products with their category and unit price, including products with no sales records
SELECT DISTINCT p.ProductID,
       p.ProductNAME,
     c.CategoryNAME,
     o.UnitPrice
FROM products AS p
LEFT JOIN order_details AS o
USING (productID)
LEFT JOIN categories AS c
USING (categoryID);

-- # Identify products that have never been ordered.
SELECT p.ProductName,
       o.OrderID AS orders
FROM products AS p
LEFT JOIN order_details AS o
USING (ProductID)
WHERE O.OrderID IS NULL;

-- # Calculate the total revenue generated by each product category and rank the categories from highest to lowest revenue.
SELECT c.CategoryID,
       c.CategoryName,
       SUM(o.UnitPrice * o.Quantity) AS total_revenue 
FROM products AS p
INNER JOIN order_details AS o
USING(ProductID)
INNER JOIN categories AS c
USING(CategoryID)
GROUP BY CategoryName, CategoryID
ORDER BY total_revenue DESC;

-- # Identify the top five products that generated the highest total profit.
SELECT p.ProductID,
       p.ProductName,
       SUM((o.UnitPrice - o.UnitCost)*o.Quantity) AS total_profit
FROM products AS p
INNER JOIN order_details AS o
USING(ProductID)
GROUP BY p.ProductID, p.ProductName 
ORDER BY total_profit DESC 
LIMIT 5;


-- # Identify product categories that generated more than $50,000 in total profit, ranked from highest to lowest profit.
SELECT c.CategoryID,
       c.CategoryName,
       SUM((o.Unitprice - o.Unitcost)*o.Quantity)AS total_profit
FROM products AS p
INNER JOIN order_details AS o
USING(ProductID)
INNER JOIN categories AS c
USING(CategoryID)
GROUP BY c.CategoryID, c. CategoryName
HAVING total_profit > 50000
ORDER BY total_profit DESC;

-- # Identify products whose total revenue is higher than the average product revenue.
WITH revenue AS (
    SELECT
        p.ProductID,
        p.ProductName,
        SUM(o.UnitPrice * o.Quantity) AS total_revenue
    FROM products AS p
    INNER JOIN order_details AS o
        USING(ProductID)
    GROUP BY p.ProductID, p.ProductName
)
SELECT
    ProductID,
    ProductName,
    total_revenue
FROM revenue
WHERE total_revenue > (
    SELECT AVG(total_revenue)
    FROM revenue
);

-- # Identify any product category whose revenue accounts for exactly 45% of total revenue.
WITH revenue AS(
SELECT p.CategoryID,
       SUM(o.UnitPrice * o.Quantity) AS category_revenue
FROM products AS p
INNER JOIN order_details AS o
USING(ProductID)
GROUP BY p.CategoryID
)
SELECT CategoryID,
       category_revenue
FROM revenue 
WHERE category_revenue = (0.45)*(
SELECT SUM(category_revenue)
FROM revenue
)
GROUP BY categoryID, Category_revenue;


-- # Compare the number of distinct product categories purchased between May and June 2026.

SELECT
    CASE
        WHEN o.OrderDate >= '2026-05-01'
             AND o.OrderDate < '2026-06-01'
            THEN 'MAY 2026'

        WHEN o.OrderDate >= '2026-06-01'
             AND o.OrderDate < '2026-07-01'
            THEN 'JUNE 2026'
    END AS month,

    COUNT(DISTINCT p.CategoryID) AS categories_purchased

FROM orders AS o

INNER JOIN order_details AS od
USING (OrderID)

INNER JOIN products AS p
USING (ProductID)

WHERE o.OrderDate >= '2026-05-01'
  AND o.OrderDate < '2026-07-01'

GROUP BY month
ORDER BY month;

-- # Compare the revenue generated by each product category between May and June 2026.
SELECT
    CASE
        WHEN o.OrderDate >= '2026-05-01'
             AND o.OrderDate < '2026-06-01'
            THEN 'MAY 2026'
        WHEN o.OrderDate >= '2026-06-01'
             AND o.OrderDate < '2026-07-01'
            THEN 'JUNE 2026'
    END AS month,
    c.CategoryID,
    c.CategoryName,
    SUM(od.UnitPrice * od.Quantity) AS revenue
FROM orders AS o
INNER JOIN order_details AS od
    USING (OrderID)
INNER JOIN products AS p
    USING (ProductID)
INNER JOIN categories AS c
    USING (CategoryID)
WHERE o.OrderDate >= '2026-05-01'
  AND o.OrderDate < '2026-07-01'
GROUP BY month,
         c.CategoryID,
         c.CategoryName
ORDER BY month,
         revenue DESC;

-- # Compare each product category's revenue between May and June 2026, calculate the revenue change and percentage change, and classify whether performance improved, declined, or stayed the same.
WITH category_may_revenue AS (
    SELECT
        p.CategoryID,
        SUM(od.UnitPrice * od.Quantity) AS may_revenue
    FROM orders AS o
    INNER JOIN order_details AS od
        USING (OrderID)
    INNER JOIN products AS p
        USING (ProductID)
    WHERE o.OrderDate >= '2026-05-01'
      AND o.OrderDate < '2026-06-01'
    GROUP BY p.CategoryID
),
category_june_revenue AS (
    SELECT
        p.CategoryID,
        SUM(od.UnitPrice * od.Quantity) AS june_revenue
    FROM orders AS o
    INNER JOIN order_details AS od
        USING (OrderID)
    INNER JOIN products AS p
        USING (ProductID)
    WHERE o.OrderDate >= '2026-06-01'
      AND o.OrderDate < '2026-07-01'
    GROUP BY p.CategoryID
)
SELECT
    c.CategoryID,
    c.CategoryName,
    COALESCE(m.may_revenue, 0) AS may_revenue,
    COALESCE(j.june_revenue, 0) AS june_revenue,
    COALESCE(j.june_revenue, 0)
    - COALESCE(m.may_revenue, 0) AS revenue_change,
    CASE
        WHEN COALESCE(j.june_revenue, 0) >
             COALESCE(m.may_revenue, 0)
            THEN 'category improved'
        WHEN COALESCE(j.june_revenue, 0) <
             COALESCE(m.may_revenue, 0)
            THEN 'category declined'
        ELSE 'no change'
    END AS performance,
    CASE
        WHEN COALESCE(m.may_revenue, 0) = 0
            THEN NULL
        ELSE
            (
                COALESCE(j.june_revenue, 0)
                - COALESCE(m.may_revenue, 0)
            ) * 100.0
            / m.may_revenue
    END AS percentage_change
FROM categories AS c
LEFT JOIN category_may_revenue AS m
    USING (CategoryID)
LEFT JOIN category_june_revenue AS j
    USING (CategoryID)
ORDER BY percentage_change DESC;


-- # Identify products that were sold in May 2026 but had no sales in June 2026.
WITH quantity_in_may AS (
    SELECT
        p.ProductID,
        p.ProductName,
        SUM(od.Quantity) AS may_quantity
    FROM products AS p
    INNER JOIN order_details AS od
        USING (ProductID)
    INNER JOIN orders AS o
        USING (OrderID)
    WHERE o.OrderDate >= '2026-05-01'
      AND o.OrderDate < '2026-06-01'
    GROUP BY p.ProductID, p.ProductName
),
quantity_in_june AS (
    SELECT
        p.ProductID,
        SUM(od.Quantity) AS june_quantity
    FROM products AS p
    INNER JOIN order_details AS od
        USING (ProductID)
    INNER JOIN orders AS o
        USING (OrderID)
    WHERE o.OrderDate >= '2026-06-01'
      AND o.OrderDate < '2026-07-01'
    GROUP BY p.ProductID
)
SELECT
    m.ProductID,
    m.ProductName,
    m.may_quantity
FROM quantity_in_may AS m
LEFT JOIN quantity_in_june AS j
    USING (ProductID)
WHERE j.ProductID IS NULL;

-- # Identify products that were sold in May 2026 but had no sales in June 2026.
WITH quantity_in_may AS (
    SELECT
        p.ProductID,
        p.ProductName,
        SUM(od.Quantity) AS may_quantity
    FROM products AS p
    INNER JOIN order_details AS od
        USING (ProductID)
    INNER JOIN orders AS o
        USING (OrderID)
    WHERE o.OrderDate >= '2026-05-01'
      AND o.OrderDate < '2026-06-01'
    GROUP BY p.ProductID, p.ProductName
),
quantity_in_june AS (
    SELECT
        p.ProductID,
        SUM(od.Quantity) AS june_quantity
    FROM products AS p
    INNER JOIN order_details AS od
        USING (ProductID)
    INNER JOIN orders AS o
        USING (OrderID)
    WHERE o.OrderDate >= '2026-06-01'
      AND o.OrderDate < '2026-07-01'
    GROUP BY p.ProductID
)
SELECT
    m.ProductID,
    m.ProductName,
    m.may_quantity
FROM quantity_in_may AS m
LEFT JOIN quantity_in_june AS j
    USING (ProductID)
WHERE j.ProductID IS NULL;